# -*- coding: utf-8 -*-
"""Canva personal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-xHuGuxK66ihx5sU8keAn7kHN1EOaas
"""

#canva personal
# Estas son mis variables tipo texto
# Arreglos (listas) con los productos y servicios disponibles

Lista_de_productos = [
    " Velas personalizadas",
    " velas aromaticas",
    " velas decorativas"
    " Velones temáticos de manifestación (gratitud, abundancia, paz interior)",
    " Kit de manifestación (velas + guía + tarjetas)",
]

print("Productos y servicios disponibles:")
print(Lista_de_productos)
print("Producto principal:", Lista_de_productos[0])
print("Producto más completo:", Lista_de_productos[2])

# Número de productos y servicios disponibles
total_oferta = len(Lista_de_productos)
print("Total de productos y servicios en la oferta:", total_oferta)

# Diccionario con herramientas o recursos del negocio
Recursos_del_negocio = {
    "Cera vegetal y esencias naturales": "Base principal para las velas artesanales",
    "Envases de vidrio": "Contienen las velas y permiten una presentación estética",
    "Impresora para etiquetas personalizadas": "Personalización con mensajes y diseños únicos",
    "Redes sociales": "Medio principal para ventas, promoción y conexión emocional con los clientes",
    "Guía de manifestación": "Contenido exclusivo que acompaña el ritual del cliente"
}

print("\nRecursos clave del negocio:")
print(Recursos_del_negocio)

# Mostrando información específica
print("La cera vegetal sirve para:", Recursos_del_negocio["Cera vegetal y esencias naturales"])
print("Las redes sociales son útiles para:", Recursos_del_negocio["Redes sociales"])

# Definir una función para describir un producto o servicio
def describir_oferta(oferta):
    print("Este producto o servicio es: " + oferta)

describir_oferta("Velas artesanales" + " Productos para manifestacion espiritual.")
describir_oferta("velas aromaticas y decorativas" + " Productos 100% artesanales con materiales naturales y mensajes de afirmacion.")

# Parámetros y condiciones según la cantidad de servicios
if total_oferta >= 5:
    print("\nMerak ofrece una variedad completa de productos y servicios de velas aromaticas.")
elif total_oferta >= 3:
    print("\nMerak cuenta con una oferta básica, pero significativa.")
else:
    print("\nSe recomienda ampliar la oferta de productos o servicios para más impacto.")

# Análisis FODA del negocio Merak
foda_merak = {
    "Fortalezas": [
        "Velas personalizadas con mensajes significativos que conectan emocionalmente",
        "Materiales de alta calidad y propuesta estética cuidada",
        "Experiencia completa con guías, mantras y ambientación",
        "Marca con propósito: fusión entre espiritualidad, diseño y autoexpresión"
    ],
    "Oportunidades": [
        "Creciente interés por el autocuidado, espiritualidad y rituales de manifestación",
        "Alta demanda en temporada decembrina y fechas especiales",
        "Posibilidad de crear comunidad digital con contenido emocional y espiritual",
        "Participación en ferias locales, colaboraciones y envíos a nivel nacional"
    ],
    "Debilidades": [
        "Marca emergente con visibilidad aún en desarrollo",
        "Producción artesanal con tiempos y capacidad limitada",
        "Presupuesto reducido para marketing y expansión",
        "Dependencia de temporadas altas para mejores ingresos"
    ],
    "Amenazas": [
        "Competencia con marcas más grandes o con mayor capacidad de difusión",
        "Clientes que priorizan precio antes que la experiencia espiritual y artesanal",
        "Aumento de costos de insumos o problemas logísticos de entrega",
        "Desinformación o escepticismo frente a productos espirituales o de intención"
    ]
}

print("\n🔍 Análisis FODA del emprendimiento Merak:")
for categoria, puntos in foda_merak.items():
    print(f"\n{categoria}:")
    for punto in puntos:
        print(f"- {punto}")